export const IPC_ACTIONS = {
  window: {
    SET_WINDOW_TITLE: 'SET_WINDOW_TITLE',
    CHECK_ACCESS_PERMISSION: 'CHECK_ACCESS_PERMISSION',
  },
  setting: {
    SAVE_SETTING: 'SAVE_SETTING',
  },
  user: {
    IMPORT_USER: 'IMPORT_USER',
    GET_LIST_USER: 'GET_LIST_USER',
    SAVE_USER: 'SAVE_EXAM',
    UPDATE_USER: 'UPDATE_USER',
    DELETE_USER: 'DELETE_USER',
  },
  exam: {
    GET_LIST_EXAM: 'GET_LIST_EXAM',
    SAVE_EXAM: 'SAVE_EXAM',
    UPDATE_EXAM: 'UPDATE_EXAM',
    DELETE_EXAM: 'DELETE_EXAM',
  },
}
